name: Online Auction CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Cấp quyền thực thi cho Maven Wrapper
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # Tạo màn hình ảo để chạy test giao diện JavaFX
      - name: Install Xvfb (Virtual Framebuffer)
        run: sudo apt-get install xvfb

      # Bước 1: Biên dịch code và chạy thử (Bỏ qua thực thi test lỗi classpath)
      - name: Run Maven Tests with Xvfb
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: xvfb-run ./mvnw clean test 

      # Bước 2: Đóng gói toàn bộ ứng dụng thành file JAR (Package này sẽ tự gom cả JavaFX và ControlsFX)
      - name: Build Application Package
        run: ./mvnw package 

      # Bước 3: Đẩy file JAR tìm thấy trong thư mục target lên GitHub cho bạn tải về
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: online-auction-client-jar
          path: target/*.jar
