name: Online Auction CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Cấp quyền thực thi cho Maven Wrapper
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # Tạo màn hình ảo để chạy test giao diện JavaFX
      - name: Install Xvfb (Virtual Framebuffer)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Bước 1: Chạy Test (Đã truyền đủ Secret Database)
      - name: Run Maven Tests with Xvfb
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: xvfb-run ./mvnw clean test

      # Bước 2: Đóng gói Client ngay tại job này thành file ZIP
      - name: Build JavaFX App using jlink
        run: ./mvnw javafx:jlink

      # Bước 3: Đẩy file app.zip lên GitHub để bạn tải về (Đã sửa thành v4)
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: online-auction-client
          path: target/auction-client.zip
